name: Workflow 2

on:
  workflow_dispatch:  # Triggered manually or by the API call from Workflow 1

jobs:
  run-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo statement
        run: echo "Workflow 2 triggered by Workflow 1"
